exclude: '.git'
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        files: 'test_utils.*'
        exclude: '.*json$|.*txt$|.*csv|.*md|.*svg'
      - id: check-yaml
      - id: no-commit-to-branch
        args: ['--branch', 'develop']
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell

  - repo: local
    hooks:
      - id: validate_javascript_dependencies
        always_run: true
        name: pre-commit/validate_javascript_dependencies.py
        entry: python3 pre-commit/validate_javascript_dependencies.py
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: validate_python_dependencies
        always_run: true
        name: pre-commit/validate_python_dependencies.py
        entry: python3 pre-commit/validate_python_dependencies.py
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: validate_customizations
        always_run: true
        name: pre-commit/validate_customizations.py
        entry: python3 pre-commit/validate_customizations.py
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: validate_copyright
        always_run: true
        name: pre-commit/validate_copyright.py
        # give app_name in entry python3 pre-commit/validate_copyright.py {app_name}
        entry: python3 pre-commit/validate_copyright.py {app_name}
        language: system
        types: [python]

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false